name: Build, test, test all examples

on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  LOG_LEVEL: info

jobs:
  build-and-test:
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
        example:
          [
            pact-js-ruby,
            pact-js-rust,
          ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fix node-gyp
        if: matrix.example == 'pact-js-rust' && runner.os == 'Windows'
        run: |-
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
        shell: pwsh
      - name: run example ${{ matrix.example }}
        run: |
          npm install       
          npm test       
        shell: bash
        working-directory: examples/${{ matrix.example }}
        env:
          NODE_VERSION: ${{ matrix.node-version }}
